# teacher model config, these param would overide student model's base.yml and exp class. if don't set, would use student model param value
emb_dim: 1536
num_query_heads: 12
num_kv_heads: 2
mlp_dim: 8960
num_decoder_layers: 28
head_dim: 128
model_name: 'Qwen2.5_1.5B'
rope_max_timescale: 1000000
vocab_size: 151936
qk_norm: False
logits_via_embedding: True # shared embedding weights
normalize_embedding_logits: False
dataset_type: 'pretrain_4k'
qkv_bias: True
query_chunk_size: 512
attention: 'dot_product_chunk'
load_parameters_path: gs://newproject-1-llm_base_models_europe-west4/v5p_256/7B/qwen2.5_1.5B_torch2jax_0515/checkpoints/0/items
pre_compose: False
post_compose: False
query_wise: False
key_wise: False
dense_conn: False
sliding_window_size: 2048
scan_layers: False
num_layers_per_block: 1
distill_topk: 128